
stages:
    - setup
    - test

setup:
    stage: setup
    script: bash .bootstrap.sh
    artifacts:
      untracked: true
      expire_in: '1h00m'
      paths:
        - .venv
        - .pyenv
    tags:
        - archlinux
docs:
    stage: test
    dependencies:
      - setup
    script:
      - source .venv/bin/activate && LC_ALL=C BROWSER=echo make docs
    tags:
        - archlinux

syntax:
    stage: test
    dependencies:
      - setup
    script:
      - source .venv/bin/activate && make mypy lint
    tags:
        - archlinux

py37:
    stage: test
    dependencies:
      - setup
    variables:
      PATH: ".pyenv/bin:.venv/bin:$PATH"
    script:
      - source .venv/bin/activate && make pytest
    tags:
        - archlinux
