steps:
    - label: setup
      command:
        - bash .bootstrap.sh
        - buildkite-agent artifact upload pkg/build.tar.gz
      artifact_paths: '.venv/*'

    - wait

    - label: docs
      command:
        - buildkite-agent artifact download pkg/build.tar.gz pkg/
        - source .venv/bin/activate && LC_ALL=C BROWSER=echo make docs

    - label: syntax
      command:
        - buildkite-agent artifact download pkg/build.tar.gz pkg/
        - source .venv/bin/activate && make mypy lint

    - label: app
      command:
        - buildkite-agent artifact download pkg/build.tar.gz pkg/
        - source .venv/bin/activate && make pytest
