steps:
    - label: setup
      command:
        - bash .bootstrap.sh
        - tar czf virtualenv.tar.gz .venv
      artifact_paths: 'virtualenv.tar.gz'

    - wait

    - label: docs
      command:
        - buildkite-agent artifact download virtualenv.tar.gz .
        - tar xf virtualenv.tar.gz
        - source .venv/bin/activate && LC_ALL=C BROWSER=echo make docs

    - label: syntax
      command:
        - buildkite-agent artifact download virtualenv.tar.gz .
        - tar xf virtualenv.tar.gz
        - source .venv/bin/activate && make mypy lint

    - label: app
      command:
        - buildkite-agent artifact download virtualenv.tar.gz .
        - tar xf virtualenv.tar.gz
        -  source .venv/bin/activate && make pytest
