steps:
    - label: setup
      command:
        - bash .bootstrap.sh
      artifact_paths: '.venv/*'

    - wait

    - label: docs
      command:
        - buildkite-agent artifact download build.tar.gz  && tar xf build.tar.gz && source .venv/bin/activate && LC_ALL=C BROWSER=echo make docs

    - label: syntax
      command:
        - buildkite-agent artifact download build.tar.gz  && tar xf build.tar.gz && source .venv/bin/activate && make mypy lint

    - label: app
      command:
        - buildkite-agent artifact download build.tar.gz  && tar xf build.tar.gz && source .venv/bin/activate && make pytest
